### ISSUE TITLE
Error exporting report to JSON when using the CLI interface

### ISSUE THREAD

**Issue by ehennestad** [NeurodataWithoutBorders/nwbinspector#533]
### What happened?

 I got the error below when I tried to export a json report using the CLI of nwbinspector with the following command:
  
`  nwbinspector behavior_tutorial.nwb --levels importance --json-file-path nwbinspector_report.json
`  

Error message:
    '
     Inspecting NWBFiles...:   0%|                                                                   | 0/1 [00:00<?, ?it/s]
     Inspecting NWBFiles...: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.81it/s]
                                                                                                                           
     Traceback (most recent call last):
       File "/Library/Frameworks/Python.framework/Versions/3.11/bin/nwbinspector", line 8, in <module>
         sys.exit(_inspect_all_cli())
                  ^^^^^^^^^^^^^^^^^^
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
         return self.main(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
         rv = self.invoke(ctx)
              ^^^^^^^^^^^^^^^^
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
         return ctx.invoke(self.callback, **ctx.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
         return __callback(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nwbinspector/_inspection_cli.py", line 141, in _inspect_all_cli
         json.dump(obj=json_report, fp=fp, cls=InspectorOutputJSONEncoder)
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 179, in dump
         for chunk in iterable:
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 432, in _iterencode
         yield from _iterencode_dict(o, _current_indent_level)
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
         yield from chunks
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
         yield from chunks
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 439, in _iterencode
         o = _default(o)
             ^^^^^^^^^^^
       File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nwbinspector/_formatting.py", line 28, in default
         if isinstance(o, Version):
                          ^^^^^^^
     NameError: name 'Version' is not defined
     '
     
Might be related to issue #396

### Operating System

macOS

### Python Version

3.11

### Were you streaming with ROS3?

No

### Package Versions

<details> Copy and paste your output here </details>
[environment_for_issue.txt](https://github.com/user-attachments/files/17747540/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by stephprince** [comment]
@ehennestad thanks for sharing the environment file - it looks like you're using an older version of nwbinspector (v0.4.37) where the `Version` import was missing in the `_formatting.py` file. It should be fixed by https://github.com/NeurodataWithoutBorders/nwbinspector/pull/520

Would you be able to update to the latest version and see if the error persists?

**Comment by ehennestad** [comment]
Thanks for looking into this. I have upgraded to v0.5.2 but still get the same error.

It looks like it was fixed here: https://github.com/NeurodataWithoutBorders/nwbinspector/blob/c453b686d2201a346f8bab1cb83a78cf8eacafa4/src/nwbinspector/_formatting.py#L14

But that commit was made after the last release (v0.5.2)

**Comment by stephprince** [comment]
Sorry my mistake, I misread that those changes had made it into the last release. I am targeting the end of this week for a new nwbinspector release which should fix this issue.

**Comment by stephprince** [comment]
Closing this for now because I believe release 0.6.0 should have fixed this error, but please reopen this issue if not.
